name: prod run

on:
  workflow_dispatch:
  schedule:
    - cron: '37 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: checkout repo
        uses: actions/checkout@v6

      - name: make gradlew executable
        run: chmod +x ./gradlew

      - name: run app
        env:
          TWITCH_DROPS_API_URL: ${{ secrets.TWITCH_DROPS_API_URL }}
          TWITCH_REWARDS_API_URL: ${{ secrets.TWITCH_REWARDS_API_URL }}
          CACHE_BACKEND: gist
          DROPS_GIST_ID: ${{ secrets.DROPS_GIST_ID }}
          REWARDS_GIST_ID: ${{ secrets.REWARDS_GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
          DROPS_GIST_FILENAME: twitch-drops-cache.json
          REWARDS_GIST_FILENAME: twitch-rewards-cache.json
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_DEBUG_SEND_LATEST_CAMPAIGN: "false"
        run: ./gradlew run
